export const languages = {
  ar: 'Arabic',
  de: 'German',
  en: 'English',
  es: 'Spanish',
  fr: 'French',
  he: 'Hebrew',
  it: 'Italian',
  nl: 'Dutch',
  no: 'Norwegian',
  pt: 'Portuguese',
  ru: 'Russian',
  se: 'Sami',
  ud: '',
  zh: 'Chinese',
};
